<?php
/**
 * Generated by framework installer - Fri, 09 Oct 2015 17:45:05 +0200
*/
    class Config
    {
	const BASEDNAME	= '/webproject';
	const DBHOST	= 'localhost';
	const DB	= 'webproject';
	const DBUSER	= 'username';
	const DBPW	= 'password';
	const SITENAME	= 'Open Access';
	const SITEURL	= 'localhost.com';
	const SITENOREPLY	= 'noreply@localhost.com';
	const SYSADMIN	= 'raffprta@gmail.com';
    }
?>